name: Create and Publish Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Get short commit hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short=5 HEAD)" >> $GITHUB_ENV

      - name: Run release script
        run: bash release.sh

      - name: List release directory
        run: ls -l releases/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: release-${{ env.COMMIT_HASH }}
          release_name: release-${{ env.COMMIT_HASH }}
          body: 'Release description'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: releases/release-${{ env.COMMIT_HASH }}.zip
          asset_name: release-${{ env.COMMIT_HASH }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
