name: Create and Publish Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Get short commit hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short=5 HEAD)" >> $GITHUB_ENV

      - name: Run release script
        run: bash release.sh

      - name: List release directory
        run: ls -l releases/

      - name: Create Release
        id: create_release
        run: |
          echo "Creating release..."
          response=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"tag_name": "release-${{ env.COMMIT_HASH }}", "name": "release-${{ env.COMMIT_HASH }}", "body": "Release description"}' \
            https://api.github.com/repos/${{ github.repository }}/releases)
          echo "$response"
          upload_url=$(echo "$response" | jq -r '.upload_url' | sed "s/{?name,label}//")
          echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV

      - name: Upload Release Asset
        run: |
          echo "Uploading release asset..."
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/zip" \
            --data-binary @releases/release-${{ env.COMMIT_HASH }}.zip \
            "${{ env.UPLOAD_URL }}?name=release-${{ env.COMMIT_HASH }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
